import fs from "fs";
import path from "path";
import Head from "next/head";
import matter from "gray-matter";
import RootLayout from "../layout";
import Link from "next/link";

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join("content/posts"));

  const posts = files.map((filename) => {
    const markdownWithMeta = fs.readFileSync(
      path.join("content/posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);

    const slug = filename.split(".")[0];
    return {
      frontmatter,
      slug,
      href: `/${slug}`,
    };
  });

  return {
    props: {
      posts,
    },
  };
};

export default function Posts({ posts }) {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RootLayout>
        <h1>Posts</h1>
        <ul>
          {posts.map((post, index) => (
            <div key={index} className="post-item">
              <h3>
                <Link className="post-item-title" href={post.href}>
                  {post.frontmatter.title}
                </Link>
              </h3>
              <p className="post-item-desc">
                {post.frontmatter.description}
                <Link className="post-item-more" href={post.href}>
                  Baca &rarr;
                </Link>
              </p>
              <time className="post-item-date">{post.frontmatter.date}</time>
            </div>
          ))}
        </ul>
      </RootLayout>
    </>
  );
}
